version: '3.8'
services:
  db-test:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monitoring_test
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  app-test:
    build:
      context: .
      target: tester
    environment:
      DATABASE_URL: postgres://postgres:postgres@db-test:5432/monitoring_test
      NODE_ENV: test
      API_KEY: test-key-123
    depends_on:
      db-test:
        condition: service_healthy
    command: ['sh', '-c', 'npx prisma migrate deploy && npm run test:e2e']
