version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monitoring
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      - DATABASE_URL
      - API_KEY
      - NODE_ENV=production
    depends_on:
      - db
    ports:
      - '3000:3000'
    # ADICIONE O COMANDO DE SEED AQUI
    command:
      [
        'sh',
        '-c',
        'npx prisma migrate deploy && npx prisma db seed && node dist/main.js',
      ]

volumes:
  db-data:
